sequenceDiagram
    newHostForm->>+HostsController : compute_resource_selected(host_params)
    HostsController->> HostsController : host=refresh_host
    HostsController->> ComputeResource : cp_attrs = compute_profile_attributes_for(host.cp_id)
    HostsController->> Host : compute_attributes=(cp_attrs)
    HostsController->> +_compute : render(host, compute_resource)
    _compute->> Host : compute_object
    Host->> +ComputeResource : new_vm(compute_attributes)
    ComputeResource->> ComputeResource: fog.new(vm_instance_defaults.merge(attrs))
    ComputeResource->> -Host : vm<Fog::Server>
    Host ->> _compute : vm
    _compute->> _provider_/base : render(compute_resource, host, vm)
    _provider_/base-->> _compute  : rendered
    _compute-->> -HostsController  : rendered
    HostsController->> -newHostForm : VM_tab_html_over_AJAX
