foreman\-debug(8)
=================
:man source:  foreman-debug
:man manual:  Foreman Manual

NAME
----
foreman-debug - Foreman configuration and log collector

SYNOPSIS
--------
foreman-debug [OPTIONS]

foreman-debug -d /output/dir -a -m 9000 -v

foreman-debug -h

DESCRIPTION
-----------

Collects configuration and log data for Foreman, Smart Proxies, backend
services and system information while removing security information like
passwords, tokens and keys.

This program can be used on Foreman instances, Smart Proxy instances or
backend services separately.

SENDING INFORMATION
-------------------

Use the *foreman-debug* tool to generate a tarball with your configuration and
recent logs and send it to developers for further investigation. Note that
passwords and tokens are filtered out, but the tarball still can contain
*sensitive information*. For this reason it is recommended to send directly to
the developers, and not publicly on the mailing list for production instances.

OPTIONS
-------

The following options are available:

  --db-tables
          Include selected tables from Foreman database
  --db-dump
          Include full database dump (generates big tarball)
  --access-logs
          Include HTTP access logs

  -d DIR  Directory to place the tarball in (default /tmp/foreman-XYZ)
  -g      Skip generic info (CPU, memory, firewall etc.)
  -a      Do not generate a tarball from the resulting directory
  -m NUM  Maximum lines to keep for each file (default 5000, 0 - no limit)
  -j PRG  Filter with provided program when creating a tarball
  -p      Additionally print password patterns being filtered out
  -q      Quiet mode
  -v      Verbose mode
  -u      Upload tarball
  -h      Shows this message

SECURITY
--------

Foreman-debug includes three basic type of data that can be sensitive:

* Configuration files
* Logging files
* Data from the Foreman database

By default, foreman-debug attempts to filter out all configuration tokens that
are sensitive, such as passwords, tokens, host names or IP addresses. All log
files are included untouched and they usually contain IP addresses and
hostnames.

Foreman-debug does not include any data from Foreman database. This must be
specified as an explicit option:

Database tables (--db-tables)

Adds selection of tables from the main database, most importantly:

* Hosts and Host groups
* Subnets and Domains
* Operating systems and Media
* Provisioning templates
* Organizations and Locations
* Auth sources
* Roles
* Usernames
* Settings

Database dump (--db-dump)

Includes full database dump including all the possible passwords stored in it.
They are encrypted via token that is saved in /etc and the token is NOT included
in the tarball.

Access logs (--access-logs)

Logs from httpd (access_logs) including IP addresses of the remote clients.

CONFIGURATION
-------------

Additional configuration can be provided via configuration file that must be
stored as /etc/foreman/foreman-debug.conf. The file has shell syntax and the
following environment variables can be defined:

 - DIR: Directory to place the tarball in (string)
 - NOGENERIC:  Skip generic info (0 or 1)
 - NOTAR:  Do not create tarballs (0 or 1)
 - MAXLINES: Maximum lines to keep for files (integer)
 - COMPRESS: Compress program to pipe the tarball through (string)
 - PRINTPASS: Print passwords which are filtered out to stdout (0 or 1)
 - QUIET: Quiet mode (0 or 1)
 - VERBOSE: Verbose mode (0 or 1)
 - DEBUG: Debug mode (0 or 1)
 - UPLOAD: Upload tarball after each run (0 or 1)
 - UPLOAD_DISABLED: Permanently disable upload feature (0 or 1)
 - FILTER_WORDS: Tokens that are filtered out (shell array)

Most of the configured options are default values and can be overridden by
command line options, others are unique and can only be set via the
configuration file.

SEE ALSO
--------

*foreman-rake*(8)

GETTING HELP
------------

For support, please see http://theforeman.org/support.html, the
foreman-users@googlegroups.com mailing list or #theforeman on Freenode.
