scss:
  enabled: false

stylelint:
  enabled: true
  config_file: .stylelintrc

rubocop:
  config_file: .rubocop.yml
  version: 0.80.0

jshint:
  enabled: false

eslint:
  enabled: false

fail_on_violations: true
