scss:
  enabled: true
  config_file: .scss-lint.yml

ruby:
  config_file: .rubocop.yml

jshint:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore

fail_on_violations: true
