require:
  - rubocop-performance
  - rubocop-rails

# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce certain methods, e.g. detect over find
Style/CollectionMethods:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Rails/Blank:
  UnlessPresent: false

#Allow both ['a', 'b'], %w[a b] and %w(a b) style arrays
Style/WordArray:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/InverseMethods:
  Enabled: false

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Bundler/OrderedGems:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Layout/DotPosition:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

# disabled until we can configure "+" as concat sign
Style/LineEndConcatenation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

# Won't work with sqlite
Rails/BulkChangeTable:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  Enabled: false

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Performance/RegexpMatch:
  Enabled: false
