# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 5.1
  Include:
    - 'app/views/api/**/*.rabl'
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce certain methods, e.g. detect over find
Style/CollectionMethods:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Performance/Casecmp:
  Enabled: false

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Rails/Blank:
  UnlessPresent: false

#Allow both ['a', 'b'], %w[a b] and %w(a b) style arrays
Style/WordArray:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/InverseMethods:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
