inherit_gem:
  theforeman-rubocop:
    - lenient.yml
    - minitest.yml

inherit_from: .rubocop_todo.yml

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Metrics:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: false

Rails:
  Enabled: true

Rails/Blank:
  UnlessPresent: false

# Won't work with sqlite
Rails/BulkChangeTable:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

# Don't enforce certain methods, e.g. detect over find
Style/CollectionMethods:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false
