Layout/ArgumentAlignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor: # (new in 0.83)
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceAroundMethodCallOperator: # (new in 0.82)
  Enabled: false
Lint/DeprecatedOpenSSLConstant: # (new in 0.84)
  Enabled: false
Lint/DuplicateElsifCondition: # (new in 0.88)
  Enabled: false
Lint/MixedRegexpCaptureTypes: # (new in 0.85)
  Enabled: false
Lint/RaiseException: # (new in 0.81)
  Enabled: false
Lint/StructNewOverride: # (new in 0.81)
  Enabled: false
Lint/UriRegexp:
  Enabled: false
Style/AccessorGrouping: # (new in 0.87)
  Enabled: false
Style/ArrayCoercion: # (new in 0.88)
  Enabled: false
Style/BisectedAttrAccessor: # (new in 0.87)
  Enabled: false
Style/CaseLikeIf: # (new in 0.88)
  Enabled: false
Style/ExponentialNotation: # (new in 0.82)
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/HashAsLastArrayItem: # (new in 0.88)
  Enabled: false
Style/HashLikeCase: # (new in 0.88)
  Enabled: false
Style/RedundantAssignment: # (new in 0.87)
  Enabled: false
Style/RedundantFetchBlock: # (new in 0.86)
  Enabled: false
Style/RedundantFileExtensionInRequire: # (new in 0.88)
  Enabled: false
Style/RedundantRegexpCharacterClass: # (new in 0.85)
  Enabled: false
Style/RedundantRegexpEscape: # (new in 0.85)
  Enabled: false
Style/SlicingWithRange: # (new in 0.83)
  Enabled: false
Performance/AncestorsInclude: # (new in 1.7)
  Enabled: false
Performance/BigDecimalWithNumericArgument: # (new in 1.7)
  Enabled: false
Performance/CollectionLiteralInLoop: # (new in 1.8)
  Enabled: false
Performance/DeletePrefix:
  Enabled: false
Performance/RedundantSortBlock: # (new in 1.7)
  Enabled: false
Performance/RedundantStringChars: # (new in 1.7)
  Enabled: false
Performance/ReverseFirst: # (new in 1.7)
  Enabled: false
Performance/SortReverse: # (new in 1.7)
  Enabled: false
Performance/Squeeze: # (new in 1.7)
  Enabled: false
Performance/StringInclude: # (new in 1.7)
  Enabled: false
Rails/ActiveRecordCallbacksOrder: # (new in 2.7)
  Enabled: false
Rails/ContentTag:
  Enabled: false
Rails/FindById: # (new in 2.7)
  Enabled: false
Rails/Inquiry: # (new in 2.7)
  Enabled: false
Rails/MailerName: # (new in 2.7)
  Enabled: false
Rails/MatchRoute: # (new in 2.7)
  Enabled: false
Rails/NegateInclude: # (new in 2.7)
  Enabled: false
Rails/Pluck: # (new in 2.7)
  Enabled: false
Rails/PluckInWhere: # (new in 2.7)
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/RedundantForeignKey:
  Enabled: false
Rails/IndexBy:
  Enabled: false
Rails/IndexWith: # (new in 2.8)
  Enabled: false
Rails/RenderInline: # (new in 2.7)
  Enabled: false
Rails/RenderPlainText: # (new in 2.7)
  Enabled: false
Rails/ShortI18n: # (new in 2.7)
  Enabled: false
Rails/WhereExists: # (new in 2.7)
  Enabled: false
Minitest/AssertInDelta: # (new in 0.10)
  Enabled: false
Minitest/AssertionInLifecycleHook: # (new in 0.10)
  Enabled: false
Minitest/AssertKindOf: # (new in 0.10)
  Enabled: false
Minitest/AssertOutput: # (new in 0.10)
  Enabled: false
Minitest/AssertPathExists: # (new in 0.10)
  Enabled: false
Minitest/AssertSilent: # (new in 0.10)
  Enabled: false
Minitest/GlobalExpectations:
  Enabled: false
Minitest/LiteralAsActualArgument: # (new in 0.10)
  Enabled: false
Minitest/MultipleAssertions: # (new in 0.10)
  Enabled: false
Minitest/RefuteInDelta: # (new in 0.10)
  Enabled: false
Minitest/RefuteKindOf: # (new in 0.10)
  Enabled: false
Minitest/RefutePathExists: # (new in 0.10)
  Enabled: false
Minitest/TestMethodName: # (new in 0.10)
  Enabled: false
Minitest/UnspecifiedException: # (new in 0.10)
  Enabled: false

# This configuration was generated by
# `rubocop --auto-gen-config --exclude-limit 0`
# on 2020-03-20 17:23:14 +0100 using RuboCop version 0.80.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 168
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentOneStep, IndentationWidth.
# SupportedStyles: case, end
Layout/CaseIndentation:
  Enabled: false

# Offense count: 194
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: symmetrical, new_line, same_line
Layout/MultilineHashBraceLayout:
  Enabled: false

# Offense count: 88
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: symmetrical, new_line, same_line
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Offense count: 110
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented, indented_relative_to_receiver
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Offense count: 86
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Enabled: false

# Offense count: 3694
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 58
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Offense count: 122
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Offense count: 106
Lint/BooleanSymbol:
  Enabled: false

# Offense count: 5
Lint/DuplicateMethods:
  Enabled: false

# Offense count: 9
Lint/NonLocalExitFromIterator:
  Enabled: false

# Offense count: 66
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# Offense count: 3
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Offense count: 14
# Configuration parameters: AllowComments.
Lint/SuppressedException:
  Enabled: false

# Offense count: 119
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Enabled: false

# Offense count: 144
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 14
Lint/UriEscapeUnescape:
  Enabled: false

# Offense count: 4
# Configuration parameters: CheckForMethodsWithNoSideEffects.
Lint/Void:
  Enabled: false

# Offense count: 28
# Cop supports --auto-correct.
Minitest/AssertEmpty:
  Enabled: false

# Offense count: 26
# Cop supports --auto-correct.
Minitest/AssertEqual:
  Enabled: false

# Offense count: 149
# Cop supports --auto-correct.
Minitest/AssertIncludes:
  Enabled: false

# Offense count: 11
# Cop supports --auto-correct.
Minitest/AssertMatch:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Minitest/AssertNil:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Minitest/AssertRespondTo:
  Enabled: false

# Offense count: 47
# Cop supports --auto-correct.
Minitest/AssertTruthy:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
Minitest/RefuteEmpty:
  Enabled: false

# Offense count: 241
# Cop supports --auto-correct.
Minitest/RefuteFalse:
  Enabled: false

# Offense count: 32
# Cop supports --auto-correct.
Minitest/RefuteIncludes:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Minitest/RefuteMatch:
  Enabled: false

# Offense count: 52
Naming/AccessorMethodName:
  Enabled: false

# Offense count: 2
Naming/BinaryOperatorParameterName:
  Enabled: false

# Offense count: 21
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
# AllowedAcronyms: CLI, DSL, ACL, API, ASCII, CPU, CSS, DNS, EOF, GUID, HTML, HTTP, HTTPS, ID, IP, JSON, LHS, QPS, RAM, RHS, RPC, SLA, SMTP, SQL, SSH, TCP, TLS, TTL, UDP, UI, UID, UUID, URI, URL, UTF8, VM, XML, XMPP, XSRF, XSS
Naming/FileName:
  Enabled: false

# Offense count: 15
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?-mix:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Enabled: false

# Offense count: 30
# Configuration parameters: EnforcedStyleForLeadingUnderscores.
# SupportedStylesForLeadingUnderscores: disallowed, required, optional
Naming/MemoizedInstanceVariableName:
  Enabled: false

# Offense count: 48
# Configuration parameters: EnforcedStyle, IgnoredPatterns.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Enabled: false

# Offense count: 149
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db, os, pp
Naming/MethodParameterName:
  Enabled: false

# Offense count: 39
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Enabled: false

# Offense count: 59
# Cop supports --auto-correct.
# Configuration parameters: PreferredName.
Naming/RescuedExceptionsVariableName:
  Enabled: false

# Offense count: 46
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, normalcase, non_integer
Naming/VariableNumber:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Rails/ApplicationController:
  Enabled: false

# Offense count: 186
# Cop supports --auto-correct.
# Configuration parameters: Include.
# Include: **/test/**/*
Rails/AssertNot:
  Enabled: false

# Offense count: 28
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/CreateTableWithTimestamps:
  Enabled: false

# Offense count: 10
# Configuration parameters: EnforcedStyle.
# SupportedStyles: strict, flexible
Rails/Date:
  Enabled: false

# Offense count: 557
# Cop supports --auto-correct.
# Configuration parameters: Whitelist.
# Whitelist: find_by_sql
Rails/DynamicFindBy:
  Enabled: false

# Offense count: 39
# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Enabled: false

# Offense count: 12
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Enabled: false

# Offense count: 49
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasManyOrHasOneDependent:
  Enabled: false

# Offense count: 109
# Configuration parameters: Include.
# Include: app/helpers/**/*.rb
Rails/HelperInstanceVariable:
  Enabled: false

# Offense count: 52
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/InverseOf:
  Enabled: false

# Offense count: 13
# Configuration parameters: Include.
# Include: app/controllers/**/*.rb
Rails/LexicallyScopedActionFilter:
  Enabled: false

# Offense count: 16
# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Enabled: false

# Offense count: 84
Rails/OutputSafety:
  Enabled: false

# Offense count: 14
# Configuration parameters: Include.
# Include: **/Rakefile, **/*.rake
Rails/RakeEnvironment:
  Enabled: false

# Offense count: 3
Rails/ReflectionClassName:
  Enabled: false

# Offense count: 2
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/ReversibleMigration:
  Enabled: false

# Offense count: 398
# Configuration parameters: Blacklist, Whitelist.
# Blacklist: decrement!, decrement_counter, increment!, increment_counter, toggle!, touch, update_all, update_attribute, update_column, update_columns, update_counters
Rails/SkipsModelValidations:
  Enabled: false

# Offense count: 25
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: strict, flexible
Rails/TimeZone:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect.
Security/JSONLoad:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
Security/YAMLLoad:
  Enabled: false

# Offense count: 3
# Configuration parameters: EnforcedStyle.
# SupportedStyles: inline, group
Style/AccessModifierDeclarations:
  Enabled: false

# Offense count: 255
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 10
Style/ClassVars:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: Keywords.
# Keywords: TODO, FIXME, OPTIMIZE, HACK, REVIEW
Style/CommentAnnotation:
  Enabled: false

# Offense count: 49
Style/DoubleNegation:
  Enabled: false

# Offense count: 158
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Enabled: false

# Offense count: 386
# Configuration parameters: EnforcedStyle.
# SupportedStyles: annotated, template, unannotated
Style/FormatStringToken:
  Enabled: false

# Offense count: 3
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 177
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

# Offense count: 2
Style/IdenticalConditionalBranches:
  Enabled: false

# Offense count: 11
# Configuration parameters: AllowIfModifier.
Style/IfInsideElse:
  Enabled: false

# Offense count: 64
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/MethodCallWithoutArgsParentheses:
  Enabled: false

# Offense count: 5
Style/MixinUsage:
  Enabled: false

# Offense count: 148
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedOctalStyle.
# SupportedOctalStyles: zero_with_o, zero_only
Style/NumericLiteralPrefix:
  Enabled: false

# Offense count: 49
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 191
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 73
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, exploded
Style/RaiseArgs:
  Enabled: false

# Offense count: 64
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

# Offense count: 63
# Cop supports --auto-correct.
Style/RescueModifier:
  Enabled: false

# Offense count: 186
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
Style/StderrPuts:
  Enabled: false

# Offense count: 2
Style/StructInheritance:
  Enabled: false

# Offense count: 96
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Enabled: false
