module Api
  module V2
    class PuppetclassesController < V2::BaseController

      include Api::Version2
      include Api::TaxonomyScope

      before_filter :find_resource, :only => %w{show update destroy}
      before_filter :find_optional_nested_object, :only => [:index]

      api :GET, "/puppetclasses/", "List all puppetclasses."
      api :GET, "/systems/:system_id/puppetclasses", "List all puppetclasses for system"
      api :GET, "/system_groups/:system_group_id/puppetclasses", "List all puppetclasses for system_group"
      api :GET, "/environments/:environment_id/puppetclasses", "List all puppetclasses for environment"
      param :system_id, String, :desc => "id of nested system"
      param :system_group_id, String, :desc => "id of nested system_group"
      param :environment_id, String, :desc => "id of nested environment"
      param :search, String, :desc => "Filter results"
      param :order, String, :desc => "Sort results"
      param :page, String, :desc => "paginate results"
      param :per_page, String, :desc => "number of entries per request"

      def index
        values   = Puppetclass.search_for(*search_options) unless nested_obj
        values ||= case nested_obj
                     when System::Base, SystemGroup
                       #NOTE: no search_for on array generated by all_puppetclasses
                       nested_obj.all_puppetclasses
                     else
                       nested_obj.puppetclasses.search_for(*search_options)
                   end
        render :json => Puppetclass.classes2hash(values.paginate(paginate_options))
      end

      api :GET, "/puppetclasses/:id", "Show a puppetclass"
      api :GET, "/systems/:system_id/puppetclasses/:id", "Show a puppetclass for system"
      api :GET, "/system_groups/:system_group_id/puppetclasses/:id", "Show a puppetclass for system_group"
      api :GET, "/environments/:environment_id/puppetclasses/:id", "Show a puppetclass for environment"
      param :system_id, String, :desc => "id of nested system"
      param :system_group_id, String, :desc => "id of nested system_group"
      param :environment_id, String, :desc => "id of nested environment"
      param :id, String, :required => true, :desc => "id of puppetclass"

      def show
      end

      api :POST, "/puppetclasses/", "Create a puppetclass."
      param :puppetclass, Hash, :required => true do
        param :name, String, :required => true
      end

      def create
        @puppetclass = Puppetclass.new(params[:puppetclass])
        process_response @puppetclass.save
      end

      api :PUT, "/puppetclasses/:id/", "Update a puppetclass."
      param :id, String, :required => true
      param :puppetclass, Hash, :required => true do
        param :name, String
      end

      def update
        process_response @puppetclass.update_attributes(params[:puppetclass])
      end

      api :DELETE, "/puppetclasses/:id/", "Delete a puppetclass."
      param :id, String, :required => true

      def destroy
        process_response @puppetclass.destroy
      end

      private

      def allowed_nested_id
        %w(environment_id system_id system_group_id)
      end

    end
  end
end
