@startuml

title DB stack example

!include shared.puml
FONT

OBJECT(db, Stack)
DBSTACK

legend
-   User edits parameters on hostgroups (created based on `ParameterResource`, stored in `GroupParameter`).
-   Those parameters are applied to puppet class parameters with overrides (`ParameterOverrideResource`).
-   `ParameterOverrideResource` can use only `ParameterResources` from same stack.
end legend

@enduml
