apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: quay.io/ohadlevy/foreman:dockerfile
        args: 
        - bundle 
        - exec
        - rake
        - db:create
        - db:migrate
        - db:seed
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "db-url"
              key: "url"
        - name: RAILS_ENV
          value: "production"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
      restartPolicy: Never
