# /etc/httpd/conf.d/foreman.conf

<VirtualHost *:80>
  ServerName foreman.local.lan

  ProxyPass / http://127.0.0.1:3000/
  ProxyPassReverse / http://127.0.0.1:3000/

  RequestHeader set X-Forwarded-Proto http
</VirtualHost>

<VirtualHost *:443>
  ServerName foreman.local.lan

  SSLEngine on
  SSLCertificateFile /etc/httpd/conf.d/_wildcard.local.lan.pem
  SSLCertificateKeyFile /etc/httpd/conf.d/_wildcard.local.lan-key.pem

  SSLOptions +ExportCertData

  RequestHeader set X-Forwarded-Proto https

  RequestHeader set SSL_CLIENT_S_DN "%{SSL_CLIENT_S_DN}s"
  RequestHeader set SSL_CLIENT_CERT "%{SSL_CLIENT_CERT}s"
  RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"

  <Location "/">
    ProxyPass http://127.0.0.1:3000/
    ProxyPassReverse http://127.0.0.1:3000/
  </Location>
</VirtualHost>
