#!/bin/bash
USERNAME=$(/usr/bin/id -un)
RAKE_CMD=/usr/bin/rake
BUNDLER_CMD=""

die() {
  echo $*; exit 1
}

cd ~foreman || die "Cannot change to foreman home directory"
[ -f Gemfile ] && BUNDLER_CMD="bundle exec"
if [ $USERNAME = foreman ]; then
  RAILS_ENV=production $BUNDLER_CMD $RAKE_CMD "$@"
else
  sudo -u foreman RAILS_ENV=production -- $BUNDLER_CMD $RAKE_CMD "$@"
fi
