class AddMissingForeignKeys < ActiveRecord::Migration[5.1]
  def change
    add_foreign_key "architectures_operatingsystems", "architectures", name: "architectures_operatingsystems_architecture_id_fk"
    add_foreign_key "architectures_operatingsystems", "operatingsystems", name: "architectures_operatingsystems_operatingsystem_id_fk"
    add_foreign_key "audits", "users", name: "audits_user_id_fk"
    add_foreign_key "cached_user_roles", "roles", name: "cached_user_roles_role_id_fk"
    add_foreign_key "cached_user_roles", "users", name: "cached_user_roles_user_id_fk"
    add_foreign_key "cached_user_roles", "user_roles", name: "cached_user_roles_user_role_id_fk"
    add_foreign_key "cached_usergroup_members", "users", name: "cached_usergroup_members_user_id_fk"
    add_foreign_key "cached_usergroup_members", "usergroups", name: "cached_usergroup_members_usergroup_id_fk"
    add_foreign_key "compute_attributes", "compute_profiles", name: "compute_attributes_compute_profile_id_fk"
    add_foreign_key "compute_attributes", "compute_resources", name: "compute_attributes_compute_resource_id_fk"
    add_foreign_key "compute_resources", "http_proxies", name: "compute_resources_http_proxy_id_fk"
    add_foreign_key "config_group_classes", "config_groups", name: "config_group_classes_config_group_id_fk"
    add_foreign_key "config_group_classes", "puppetclasses", name: "config_group_classes_puppetclass_id_fk"
    add_foreign_key "domains", "smart_proxies", column: "dns_id", name: "domains_dns_id_fk"
    add_foreign_key "environment_classes", "environments", name: "environment_classes_environment_id_fk"
    add_foreign_key "environment_classes", "puppetclasses", name: "environment_classes_puppetclass_id_fk"
    add_foreign_key "environment_classes", "lookup_keys", column: "puppetclass_lookup_key_id", name: "environment_classes_puppetclass_lookup_key_id_fk"
    add_foreign_key "external_usergroups", "auth_sources", name: "external_usergroups_auth_source_id_fk"
    add_foreign_key "external_usergroups", "usergroups", name: "external_usergroups_usergroup_id_fk"
    add_foreign_key "fact_values", "fact_names", name: "fact_values_fact_name_id_fk"
    add_foreign_key "fact_values", "hosts", name: "fact_values_host_id_fk"
    add_foreign_key "features_smart_proxies", "features", name: "features_smart_proxies_feature_id_fk"
    add_foreign_key "features_smart_proxies", "smart_proxies", name: "features_smart_proxies_smart_proxy_id_fk"
    add_foreign_key "filterings", "filters", name: "filterings_filter_id_fk"
    add_foreign_key "filterings", "permissions", name: "filterings_permission_id_fk"
    add_foreign_key "filters", "roles", name: "filters_role_id_fk"
    add_foreign_key "host_classes", "hosts", name: "host_classes_host_id_fk"
    add_foreign_key "host_classes", "puppetclasses", name: "host_classes_puppetclass_id_fk"
    add_foreign_key "host_config_groups", "config_groups", name: "host_config_groups_config_group_id_fk"
    add_foreign_key "host_status", "hosts", name: "host_status_host_id_fk"
    add_foreign_key "hostgroup_classes", "hostgroups", name: "hostgroup_classes_hostgroup_id_fk"
    add_foreign_key "hostgroup_classes", "puppetclasses", name: "hostgroup_classes_puppetclass_id_fk"
    add_foreign_key "hostgroups", "architectures", name: "hostgroups_architecture_id_fk"
    add_foreign_key "hostgroups", "compute_profiles", name: "hostgroups_compute_profile_id_fk"
    add_foreign_key "hostgroups", "compute_resources", name: "hostgroups_compute_resource_id_fk"
    add_foreign_key "hostgroups", "domains", name: "hostgroups_domain_id_fk"
    add_foreign_key "hostgroups", "environments", name: "hostgroups_environment_id_fk"
    add_foreign_key "hostgroups", "media", name: "hostgroups_medium_id_fk"
    add_foreign_key "hostgroups", "operatingsystems", name: "hostgroups_operatingsystem_id_fk"
    add_foreign_key "hostgroups", "templates", column: "ptable_id", name: "hostgroups_ptable_id_fk"
    add_foreign_key "hostgroups", "smart_proxies", column: "puppet_ca_proxy_id", name: "hostgroups_puppet_ca_proxy_id_fk"
    add_foreign_key "hostgroups", "smart_proxies", column: "puppet_proxy_id", name: "hostgroups_puppet_proxy_id_fk"
    add_foreign_key "hostgroups", "realms", name: "hostgroups_realm_id_fk"
    add_foreign_key "hostgroups", "subnets", column: "subnet6_id", name: "hostgroups_subnet6_id_fk"
    add_foreign_key "hostgroups", "subnets", name: "hostgroups_subnet_id_fk"
    add_foreign_key "hosts", "architectures", name: "hosts_architecture_id_fk"
    add_foreign_key "hosts", "compute_profiles", name: "hosts_compute_profile_id_fk", on_update: :nullify, on_delete: :nullify
    add_foreign_key "hosts", "compute_resources", name: "hosts_compute_resource_id_fk"
    add_foreign_key "hosts", "environments", name: "hosts_environment_id_fk"
    add_foreign_key "hosts", "hostgroups", name: "hosts_hostgroup_id_fk"
    add_foreign_key "hosts", "images", name: "hosts_image_id_fk", on_update: :nullify, on_delete: :nullify
    add_foreign_key "hosts", "taxonomies", column: "location_id", name: "hosts_location_id_fk"
    add_foreign_key "hosts", "media", name: "hosts_medium_id_fk", on_update: :nullify, on_delete: :nullify
    add_foreign_key "hosts", "models", name: "hosts_model_id_fk"
    add_foreign_key "hosts", "operatingsystems", name: "hosts_operatingsystem_id_fk"
    add_foreign_key "hosts", "taxonomies", column: "organization_id", name: "hosts_organization_id_fk"
    add_foreign_key "hosts", "templates", column: "ptable_id", name: "hosts_ptable_id_fk"
    add_foreign_key "hosts", "smart_proxies", column: "puppet_ca_proxy_id", name: "hosts_puppet_ca_proxy_id_fk"
    add_foreign_key "hosts", "smart_proxies", column: "puppet_proxy_id", name: "hosts_puppet_proxy_id_fk"
    add_foreign_key "hosts", "realms", name: "hosts_realm_id_fk"
    add_foreign_key "images", "architectures", name: "images_architecture_id_fk"
    add_foreign_key "images", "compute_resources", name: "images_compute_resource_id_fk"
    add_foreign_key "images", "operatingsystems", name: "images_operatingsystem_id_fk"
    add_foreign_key "key_pairs", "compute_resources", name: "key_pairs_compute_resource_id_fk"
    add_foreign_key "locations_organizations", "taxonomies", column: "location_id", name: "locations_organizations_location_id_fk"
    add_foreign_key "locations_organizations", "taxonomies", column: "organization_id", name: "locations_organizations_organization_id_fk"
    add_foreign_key "logs", "messages", name: "logs_message_id_fk"
    add_foreign_key "logs", "reports", name: "logs_report_id_fk"
    add_foreign_key "logs", "sources", name: "logs_source_id_fk"
    add_foreign_key "lookup_keys", "puppetclasses", name: "lookup_keys_puppetclass_id_fk"
    add_foreign_key "lookup_values", "lookup_keys", name: "lookup_values_lookup_key_id_fk"
    add_foreign_key "media_operatingsystems", "media", name: "media_operatingsystems_medium_id_fk"
    add_foreign_key "media_operatingsystems", "operatingsystems", name: "media_operatingsystems_operatingsystem_id_fk"
    add_foreign_key "nics", "domains", name: "nics_domain_id_fk"
    add_foreign_key "nics", "hosts", name: "nics_host_id_fk"
    add_foreign_key "nics", "subnets", column: "subnet6_id", name: "nics_subnet6_id_fk"
    add_foreign_key "nics", "subnets", name: "nics_subnet_id_fk"
    add_foreign_key "notification_recipients", "notifications", name: "notification_recipients_notification_id_fk"
    add_foreign_key "notification_recipients", "users", name: "notification_recipients_user_id_fk", on_update: :cascade, on_delete: :cascade
    add_foreign_key "notifications", "notification_blueprints", name: "notifications_notification_blueprint_id_fk"
    add_foreign_key "notifications", "users", name: "notifications_user_id_fk"
    add_foreign_key "operatingsystems_provisioning_templates", "operatingsystems", name: "operatingsystems_provisioning_templates_operatingsystem_id_fk"
    add_foreign_key "operatingsystems_provisioning_templates", "templates", column: "provisioning_template_id", name: "operatingsystems_provisioning_templates_provisioning_template_id_fk"
    add_foreign_key "operatingsystems_ptables", "operatingsystems", name: "operatingsystems_ptables_operatingsystem_id_fk"
    add_foreign_key "operatingsystems_ptables", "templates", column: "ptable_id", name: "operatingsystems_ptables_ptable_id_fk"
    add_foreign_key "operatingsystems_puppetclasses", "operatingsystems", name: "operatingsystems_puppetclasses_operatingsystem_id_fk"
    add_foreign_key "operatingsystems_puppetclasses", "puppetclasses", name: "operatingsystems_puppetclasses_puppetclass_id_fk"
    add_foreign_key "os_default_templates", "operatingsystems", name: "os_default_templates_operatingsystem_id_fk"
    add_foreign_key "os_default_templates", "templates", column: "provisioning_template_id", name: "os_default_templates_provisioning_template_id_fk"
    add_foreign_key "os_default_templates", "template_kinds", name: "os_default_templates_template_kind_id_fk"
    add_foreign_key "personal_access_tokens", "users", name: "personal_access_tokens_user_id_fk"
    add_foreign_key "realms", "smart_proxies", column: "realm_proxy_id", name: "realms_realm_proxy_id_fk"
    add_foreign_key "reports", "hosts", name: "reports_host_id_fk"
    add_foreign_key "roles", "roles", column: "cloned_from_id", name: "roles_cloned_from_id_fk", on_update: :nullify, on_delete: :nullify
    add_foreign_key "ssh_keys", "users", name: "ssh_keys_user_id_fk"
    add_foreign_key "subnet_domains", "domains", name: "subnet_domains_domain_id_fk"
    add_foreign_key "subnet_domains", "subnets", name: "subnet_domains_subnet_id_fk"
    add_foreign_key "subnets", "smart_proxies", column: "dhcp_id", name: "subnets_dhcp_id_fk"
    add_foreign_key "subnets", "smart_proxies", column: "dns_id", name: "subnets_dns_id_fk"
    add_foreign_key "subnets", "smart_proxies", column: "template_id", name: "subnets_template_id_fk"
    add_foreign_key "subnets", "smart_proxies", column: "tftp_id", name: "subnets_tftp_id_fk"
    add_foreign_key "table_preferences", "users", name: "table_preferences_user_id_fk"
    add_foreign_key "taxable_taxonomies", "taxonomies", name: "taxable_taxonomies_taxonomy_id_fk"
    add_foreign_key "template_combinations", "environments", name: "template_combinations_environment_id_fk"
    add_foreign_key "template_combinations", "hostgroups", name: "template_combinations_hostgroup_id_fk"
    add_foreign_key "template_combinations", "templates", column: "provisioning_template_id", name: "template_combinations_provisioning_template_id_fk"
    add_foreign_key "templates", "template_kinds", name: "templates_template_kind_id_fk"
    add_foreign_key "tokens", "hosts", name: "tokens_host_id_fk"
    add_foreign_key "trend_counters", "trends", name: "trend_counters_trend_id_fk"
    add_foreign_key "user_mail_notifications", "mail_notifications", name: "user_mail_notifications_mail_notification_id_fk"
    add_foreign_key "user_mail_notifications", "users", name: "user_mail_notifications_user_id_fk"
    add_foreign_key "user_roles", "roles", name: "user_roles_role_id_fk"
    add_foreign_key "usergroup_members", "usergroups", column: "member_id", name: "usergroup_members_member_id_fk"
    add_foreign_key "usergroup_members", "usergroups", name: "usergroup_members_usergroup_id_fk"
    add_foreign_key "users", "auth_sources", name: "users_auth_source_id_fk"
    add_foreign_key "users", "taxonomies", column: "default_location_id", name: "users_default_location_id_fk"
    add_foreign_key "users", "taxonomies", column: "default_organization_id", name: "users_default_organization_id_fk"
    add_foreign_key "widgets", "users", name: "widgets_user_id_fk"
  end
end
