gem 'jquery-rails', '~> 3.1'
gem 'jquery-turbolinks', '~> 2.1'
gem 'jquery-ui-rails', '< 5.0.0'
gem 'autoprefixer-rails', '~> 5.2'
gem 'patternfly-sass', '>= 2.7', '< 2.10.0'
gem 'multi-select-rails', '~> 0.9'
gem 'gridster-rails', '~> 0.5'
gem 'select2-rails', '~> 3.5'
gem 'underscore-rails', '~> 1.8'
gem 'gettext_i18n_rails_js', '~> 1.0'
gem 'execjs', '>= 1.4.0', '<2.5.0'
gem 'ace-rails-ap', '~> 4.0.0'
gem 'flot-rails', '0.0.3'
gem 'uglifier', '>= 1.0.3'
gem 'sass-rails', '~> 5.0'
gem 'spice-html5-rails', '~> 0.1.5'
gem 'quiet_assets', '~> 1.0'
# Pinned until https://github.com/reactjs/react-rails/issues/431 is resolved
gem 'react-rails', '1.4.1'
gem 'c3-rails', '~> 0.4'
gem 'd3-rails', '~> 3.5'
gem 'jquery_pwstrength_bootstrap_4', :require => 'jquery_pwstrength_bootstrap'
