#! /bin/sh
# a simple script to create a Foreman Official relase.

cd /tmp
rm -rf foreman
git clone git://github.com/ohadlevy/foreman.git foreman
cd foreman
git submodule init
git submodule update

rm -rf `find -name ".git*"`
rm -rf vendor/rails/railties/guides
rake gems:refresh_specs
cd /tmp

tar cv foreman | bzip2 -9 > /tmp/foreman-$1.tar.bz2
rm -rf foreman

echo "Don't forget to tag the release"
