#! /bin/sh
# a simple script to create a Foreman Official relase.

cd /tmp
rm -rf foreman
git clone git://github.com/theforeman/foreman.git foreman --branch develop
cd foreman
git submodule init
git submodule update
bundle install --path vendor --without development test

rm -rf `find -name ".git*"`
rm -rf vendor/rails/railties/guides
rm -rf `find -name test -type d`
rm -rf `find -name spec -type d`
rm -rf `find -name "*.gem"`
cd /tmp

tar cv foreman | bzip2 -9 > /tmp/foreman-$1.tar.bz2
rm -rf foreman

echo "Don't forget to tag the release"
