---
name: Foreman

on:
  workflow_call:
    inputs:
      rake-task:
        required: true
        type: string
      matrix:
        required: true
        type: string

env:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres:password@localhost/test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
  BUNDLE_WITHOUT: "console:development:journald"

jobs:
  test:
    name: "Ruby ${{ matrix.ruby }} and Node ${{ matrix.node }} on PostgreSQL ${{ matrix.postgresql }}"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'postgres:${{ matrix.postgresql }}'
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: password
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -qq -y install build-essential libcurl4-openssl-dev zlib1g-dev libpq-dev libvirt-dev
      - name: "Check out Foreman"
        uses: actions/checkout@v4
      - name: "Set up Ruby ${{ matrix.ruby }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Archive Gemfile.lock
        uses: actions/upload-artifact@v3
        with:
          name: Gemfile-ruby-${{ matrix.ruby }}-node-${{ matrix.node }}-pg-${{ matrix.postgresql }}.lock
          path: Gemfile.lock
      - name: "Set up Node ${{ matrix.node }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Prepare test env
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run rake ${{ inputs.rake-task }}
        run: bundle exec rake ${{ inputs.rake-task }}
